# Generated by Django 5.2.8 on 2025-11-19 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_produto_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='disponivel',
            field=models.BooleanField(default=False),
        ),
    ]
