# Generated by Django 5.2.8 on 2025-11-19 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_produto_disponivel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='disponivel',
        ),
    ]
