# Generated by Django 5.2.8 on 2025-11-19 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_remove_produto_disponivel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoafisica',
            name='site',
        ),
    ]
