# Generated by Django 5.2.8 on 2025-11-26 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0006_remove_pessoafisica_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoafisica',
            name='endereco',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='market.endereco'),
        ),
        migrations.AlterField(
            model_name='pessoajuridica',
            name='endereco',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='market.endereco'),
        ),
    ]
